kubernetesClusterDomain: cluster.local

controllerManager:
  replicas: 1
  manager:
    image:
      repository: ""
      tag: ""
    env:
      leaderElection: "true"
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - "ALL"
      seccompProfile:
        type: RuntimeDefault
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
  serviceAccount:
    annotations: {}
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

webhookService:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      appProtocol: https
      targetPort: 9443

serviceAccount:
  create: true
  name: ""
